### ISSUE TITLE
Python Drawback: development environment

### ISSUE THREAD

**Issue by jhillairet** [scipy-lectures/scipy-lecture-notes#108]
First of all, many thanks for this fabulous resource !

It is stated in the first section that a drawback of Python is that Python has a "less pleasant development environment than, for example, Matlab. (More geek-oriented).". 

Of course it is very true is one talks about pure python or ipython from the command line. But it exists fancy GUI to develop in Python, close to to the Matlab's user experience (e.g. Spyder, ...). I would not like that a reader believes that there is no such tools. 

I understand that naming directly a project and not some other can be problematic, but at least a sentence explaining that there is such GUIs would help new Python users.

Regards,

**Comment by GaelVaroquaux** [comment]
Indeed, we should point out to the jupyter notebook, spyder, pycharm, and be more positive, as these days, things are pretty sweet with Python.
