### ISSUE TITLE
Optimization: what about SGD?

### ISSUE THREAD

**Issue by MInner** [scipy-lectures/scipy-lecture-notes#109]
I'm not an expert, but googling for a while tells me that when you can estimate gradient or if you have tons of training samples (when used in machine learning) then using SGD can be even more efficient than BFGS(-L).

http://metaoptimize.com/qa/questions/785/online-optimization-algorithms-are-there-good-implementations-libraries-to-use

http://www.quora.com/Machine-Learning/Is-the-L-bfgs-always-better-than-stochastic-gradient-descent

It seems to me that it should be somehow represented in docs. :) Thanks.

**Comment by GaelVaroquaux** [comment]
SGD is great, and I use it heavily in machine learning. However, it is a very specific use case, specific in it's input data (statistical data), in it's way of being used, and in it's goal (it doesn't reach very low enery). In addition, it is fragile, as it requires tweaking the "learning rate", which is an open research question.


So, I disagree that it stands in a general-purpose tutorial optimization.

This is an opinion of a machine learning researcher, with a very serious interest in SGD, by the way: I love SGD.

**Comment by MInner** [comment]
AFAIK, it is proved to converge in convex case if the objective function is the sum of function applied on many let's say, data points. Then, taking derivative wrt some subset of sum elements should work fine.
