### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by matthew-brett** [scipy-lectures/scipy-lecture-notes#130]
Very nice set of documents - thanks for this.

I am planning to teach with Python 3 - do you have any plans / suggestions for what do with Python 3 edits to these notes?

**Comment by esc** [comment]
Hard to say for sure. Ideally some kind of translation mechanism would be a possibility. For example, to have a feature switch that allows generating the notes for Py2 and Py3 but from the same source code.

**Comment by esc** [comment]
Another option is to maintain a patch-stack or translation branch that is continuously rebased.. We don't see too many edits anymore (the notes are fairly old already) so that might be viable.

**Comment by GaelVaroquaux** [comment]
Well, a first think that we could do, is do all the simple changes, such
a parenthesis on prints.

**Comment by GaelVaroquaux** [comment]
I am closing this, as it has been implemented in master. We will have a release anytime (I hope today or tomorrow).
