### ISSUE TITLE
Casting example not reproducible

### ISSUE THREAD

**Issue by rcrehuet** [scipy-lectures/scipy-lecture-notes#132]
Hi,
When I try to execute the casting example in https://scipy-lectures.github.io/advanced/advanced_numpy/index.html#casting the `y+256` returns a broadcasted array to int16 not int8.

    >>> x = np.array([1, 2, 3, 4], dtype=np.float)
    >>> y = x.astype(np.int8)
    >>> y + 256
    array([257, 258, 259, 260], dtype=int16)

I am using Python 3.4 and numpy 1.8.2. (the same happens with Python 2.7)

**Comment by emmanuelle** [comment]
Thank you for the issue. It has been fixed by #161. Therefore I'm closing the issue.
