### ISSUE TITLE
Section "Module Loading" Has Typo

### ISSUE THREAD

**Issue by muraii** [scipy-lectures/scipy-lecture-notes#134]
It seems that the importing of _demo2.py_ shouldn't create output of "b".

http://scipy-lectures.github.io/intro/language/reusing_code.html#main-and-module-loading

**Comment by esc** [comment]
Almost correct, in fact ``demo2.py`` shouldn't print ``sys.argv`` but ``b``. Please submit a pull-request.

**Comment by muraii** [comment]
I see that you're pulling in `demo2.py` with `.. literalinclude:: demo2.py`, and `demo2.py` correctly defines `print_b()`:

```python
# print_b() runs on import
print_b()```

The `demo2.py` in the rendered guide does not match the `demo2.py` of the repo:

```python
import sys

def print_a():
    "Prints a."
    print 'a'

print sys.argv

if __name__ == '__main__':
    print_a()```

vs.

```python
def print_b():
    "Prints b."
    print 'b'

def print_a():
    "Prints a."
    print 'a'

# print_b() runs on import
print_b()

if __name__ == '__main__':
    # print_a() is only executed when the module is run directly.
    print_a()```

There's nothing to correct in the fork. Maybe GitHub just needs to rerender the guide?

**Comment by esc** [comment]
Thanks for investigating, looks like it is time for a new release afterall.
