### ISSUE TITLE
Improve the CSS

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#137]
* Check that it renders well on mobile phone

* Use PureCSS for the above, and because it looks cooler

* Add a "table of contents" that (models are http://nilearn.github.io/introduction.html#python-for-neuroimaging-a-quick-start http://bokeh.pydata.org/en/latest/, the design of bokeh being nicer):

   - Doesn't scroll down
   - Highlights the current section
   - Disappears on small screens (mobile friendly + tutorial friendly)

**Comment by NelleV** [comment]
I can work on this.

**Comment by raquel-ucl** [comment]
I can help as well

**Comment by GaelVaroquaux** [comment]
The sidebar is now implemented in master. Mobile work OK. Closing.
