### ISSUE TITLE
Use sphinx-gallery

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#138]
We can throw away our gen_rst.py and use sphinx gallery.

Once this is done, we can use it's cool features, like the fact that you can have multiple sub gallery, and the notebook-style examples.

**Comment by djarecka** [comment]
trying

**Comment by GaelVaroquaux** [comment]
@titan-C should be able to help with this.

**Comment by GaelVaroquaux** [comment]
Closed as implemented by #257
