### ISSUE TITLE
Use travis-ci to run our doc tests

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#139]
On Python 2 and python 3: we need to run doc-test on the documentation, elsewhere it ends up broken (and fix them).

We can mimic the way nilearn does it to use miniconda for python 3
https://github.com/nilearn/nilearn 

To run examples, we can use circle-ci, as done in nilearn, because it gives you much more computing power, and can cache dowloads in a persistent way across different runs.

**Comment by vahtras** [comment]
This was fixed at the Euroscipy sprints I beleive. Closing.
