### ISSUE TITLE
Add a tooltip to the ">>>" magic button on the code examples

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#142]
Using simple CSS plus html (eg as in the sphinx-gallery http://nilearn.github.io/auto_examples/index.html) we can add a tooltip that pops up on hover for the magic ">>>" that goes with the code prompts. That would strongly increase the discoverability of this feature.

**Comment by raquel-ucl** [comment]
I can work on this.

**Comment by GaelVaroquaux** [comment]
Closed as fixed by 3b0bf84

Sorry, @raquel-ucl, we needed to do a release so I went forward and did a little to enable this.
