### ISSUE TITLE
Make doctest pass reliably

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#145]
We need to move to more doctesting, which will force us to have more testable code.

Steps are

* [ ] Run 'make test', fix the failing, skip the rest
* [ ] Convert code snippets to use doctest-like syntax (eg those using IPython prompts or chunks of code without prompts
* [ ] Fix the resulting problems by adding things like doctest ellipsis, normalise white-space or skipping the test

**Comment by pdebuyl** [comment]
I'll join this
