### ISSUE TITLE
Make the >>> text in the example unselectable

### ISSUE THREAD

**Issue by raquel-ucl** [scipy-lectures/scipy-lecture-notes#151]
Users who want to copy and paste from the examples have to click on the `>>>` button to filter out the `>>>` symbols. It'd be nice to get rid of the `>>>` button and just make the `>>>` text in the textarea unselectable like in [this example](https://jsfiddle.net/raquelalegre/nw0uw6zc/).

Note JsFiddle doesn't work as a normal website and although the highlight behaviour works for this example, it's actually saving all the text in the clipboard. It'll work properly in "real" websites.

**Comment by GaelVaroquaux** [comment]
Reopening: wrong issue number, the commit fixes #142

**Comment by pdebuyl** [comment]
Isn't this fixed by now?

**Comment by GaelVaroquaux** [comment]
> Isn't this fixed by now?

No. This issue is about using specific tags (that I do not know) that
makes it that the ">>>" is skipped when using the mouse to select text.

**Comment by pdebuyl** [comment]
Ok. The sphinx theming loads the pygment-generated css that cannot have html-specific styling. The best way seems to add a custom css file that complements the prompt styling with the above properties.

To avoid selecting the output as well (that is not wished for copy-pasting the input only), I suggest to also prevent the selection of the prompt output. The css classes are ".gp" (for general prompt) and ".go".

Only issue: if someone really wishes to copy the output of a command, that is not possible anymore.

PR coming.

**Comment by pdebuyl** [comment]
Fixed by #330
