### ISSUE TITLE
Errors and warnings during "make html": plot_gradient_descent.py

### ISSUE THREAD

**Issue by vahtras** [scipy-lectures/scipy-lecture-notes#187]
There are several, but I will start with one:

plot_gradient_descent.py is not compiling:
Traceback (most recent call last):
  File "/home/vahtras/Courses/scipy-lecture-notes/sphinxext/gen_rst.py", line 236, in generate_file_rst
    execfile(os.path.basename(src_file), {'pl' : plt})
  File "plot_gradient_descent.py", line 175, in <module>
    hessian=counting_hessian)
  File "plot_gradient_descent.py", line 65, in gradient_descent_adaptative
    return gradient_descent(x0, f, f_prime, adaptative=True)
  File "plot_gradient_descent.py", line 57, in gradient_descent
    x_i += - step*dx_i
TypeError: bad operand type for unary -: 'NoneType'

The error is due to 'step' being None, which is returned from scipy.optimize.line_search when the procedure fails to converge. 

Should we fix or drop the example? The initial comment says 

\# A gradient descent algorithm
\# do not use: its a toy, use scipy's optimize.fmin_cg

**Comment by GaelVaroquaux** [comment]
I need to fix the example (it's easy, I'll do it).

This example useful to create the figures, that are didactic (I was just
sitting in a signal-processing conference today, and one speaker was
using these to explain gradient descent).

**Comment by GaelVaroquaux** [comment]
I have create a PR to fix this: #188 . I have checked that the figures generated are the same as the ones on line.
