### ISSUE TITLE
More build errors: scikit-image/index.rst

### ISSUE THREAD

**Issue by vahtras** [scipy-lectures/scipy-lecture-notes#189]
$ make html
    ...
    /home/olav/courses/scipy-lecture-notes/packages/scikit-image/index.rst:458: SEVERE: Title level inconsistent:

    Binary segmentation: foreground + background
    .............................................

The subsection is empy and has an inconsistent level. The header does not show up in the final html and I don't really know what to make of it.

**Comment by GaelVaroquaux** [comment]
Good catch. I'll have a look at it, and fix ASAP.
