### ISSUE TITLE
Time for rebuild?

### ISSUE THREAD

**Issue by matthew-brett** [scipy-lectures/scipy-lecture-notes#192]
Would y'all consider uploading a current version of the lectures?  We're admiring the introduction to bumpy, but it still has the recommendation to use `--pylab` removed by #133 .  Maybe there are other useful changes that would be good to publish?

**Comment by GaelVaroquaux** [comment]
Yes, we need to do a new release. Amongst other things the lectures have
been ported to Python 3. I was waiting for a few pull requests that I
have been promised before doing a release. It should happen in the next
couple of weeks hopefully.

**Comment by rougier** [comment]
I'll try to make a PR for the matplotlib chapter and removed the pylab stuff.

**Comment by GaelVaroquaux** [comment]
> I'll try to make a PR for the matplotlib chapter and removed the pylab
> stuff.

That's great. Thanks!

**Comment by GaelVaroquaux** [comment]
Closing as fixed!

Sorry it took so long, there was a fair amount of QA to do.

**Comment by matthew-brett** [comment]
Thanks a lot for doing that.
