### ISSUE TITLE
Build errors: seaborn.pairplot

### ISSUE THREAD

**Issue by vahtras** [scipy-lectures/scipy-lecture-notes#193]
What versions should we aim at? In standard ubuntu the seaborn version is 0.4 and the `markers` keyword is not supported. The latest version is 0.6

    plot_airfare.py is not compiling:
    Traceback (most recent call last):
      File "/home/vahtras/courses/scipy-lecture-notes/sphinxext/gen_rst.py", line 695, in generate_file_rst
        execfile(os.path.basename(src_file), my_globals)
      File "plot_airfare.py", line 77, in <module>
        kind='reg', markers='.')
    TypeError: pairplot() got an unexpected keyword argument 'markers'

**Comment by vahtras** [comment]
By standard, I mean the latest ubuntu distribution 15.04. Next ubuntu distribution 15.10 will have seaborn 0.6

**Comment by GaelVaroquaux** [comment]
Indeed. Because this is such a useful feature, I was hoping that we could, for this feature only, have an example that runs only on more recent versions. I have added this in the text of the lecture notes.  Maybe I should add this as a note in the example. What do you think?

**Comment by vahtras** [comment]
That's a good idea. OK we will leave it and next  Ubuntu is less than a
month away...
-Olav

**Comment by vahtras** [comment]
Not relevant any more - Closing issue
