### ISSUE TITLE
The Python language does not have ToC sidebar

### ISSUE THREAD

**Issue by rougier** [scipy-lectures/scipy-lecture-notes#201]
On Safari, OSX, the python language section does not have a ToC sidebar.

Same for Numpy section.

**Comment by GaelVaroquaux** [comment]
> On Safari, OSX, the python language section does not have a ToC sidebar.

Everywhere: the corresponding page have no sub section, they are in other
pages.

I believe that this is "not a bug".

**Comment by GaelVaroquaux** [comment]
Closing this. Partly because I don't know how to fix this. If you have a fix in mind, don't hesitate to reopen.
