### ISSUE TITLE
Too deep numbering ?

### ISSUE THREAD

**Issue by rougier** [scipy-lectures/scipy-lecture-notes#202]
4 levels for numbering might be a bit too much (see http://www.scipy-lectures.org/intro/language/python_language.html)

Can't we stop numbering after 3rd level ?

**Comment by GaelVaroquaux** [comment]
On this specific page it seemed OK to me (on others, it seems to me that
the "chapter contents" is too deep).

**Comment by GaelVaroquaux** [comment]
@rougier : do you know how to do this in sphinx?

**Comment by rougier** [comment]
I don't know but I'll search.

**Comment by rougier** [comment]
It could be fixed using the [sectnum](http://docutils.sourceforge.net/docs/ref/rst/directives.html#sectnum) but unfortunatley, Sphinx recommends [to not use it](http://www.sphinx-doc.org/en/stable/rest.html#directives):

```
Do not use the directives sectnum, header and footer.
```

**Comment by GaelVaroquaux** [comment]
Fixed in master
