### ISSUE TITLE
Integrate Thebe for interactive IPython notebooks

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#204]
https://oreillymedia.github.io/thebe/
It's a javascript library that can turn a static page with code snippets into an interactive one.

**Comment by fperez** [comment]
@Carreau, do you have M. Pacer's github ID so we can ping him? He has a prototype of this already working...

**Comment by GaelVaroquaux** [comment]
> @Carreau, do you have M. Pacer's github ID so we can ping him? He has a prototype of this already working...

That would be awesome! Taking teaching to the next level!

**Comment by Carreau** [comment]
Yep, @michaelpacer your needed here. 

The prototype is there: http://michaelpacer.github.io/thebe-test/ . You need a server on localhost that allow-origin='*' for now, which is not recommended for security reason. 


@GaelVaroquaux I think it might be a nice feature to add to sphinx-gallery too.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux I think it might be a nice feature to add to sphinx-gallery too.

Agreed. Or maybe even binder support for actual notebooks generated from
sphinx-gallery, which should come soon.

**Comment by michaelpacer** [comment]
I didn't know that there was work on generating notebooks from
sphinx-gallery, I'd been looking in how to do that just using vanilla
sphinx. Sounds great!

I may need to make a new repo to for the source sphinx files and the
template needed to make it happen. I'm a bit pressed for time at the
moment, but the other big step is to have it work on a tmpnb inside of a
docker instance.

And as for the binder support that was where I was seeing it going next
too. Huzzah for open-source allowing projects to converge like this :).
