### ISSUE TITLE
Minor mistake in section 1.3.1

### ISSUE THREAD

**Issue by JQFonseca** [scipy-lectures/scipy-lecture-notes#219]
Great resource thank you for the hard work.

In section 1.3.1.4 it says:

Or, if you have enabled interactive plots with %matplotlib:
>>> plot(x, y)       # line plot    

should be plt.plot(x,y) I think.

**Comment by pdebuyl** [comment]
You are right, `%matplotlib` adds `plt` to the namespace but not the functions themselves.
