### ISSUE TITLE
Make code compatible with Python 3

### ISSUE THREAD

**Issue by gertingold** [scipy-lectures/scipy-lecture-notes#243]
Some code examples are specific for Python 2. For example, in some places `xrange` is used. It would be better to modify the code to make it compatible with Python 2 and Python 3.

**Comment by pdebuyl** [comment]
Can this issue be closed, as the code is now working with Python 2/3 and that "Python 2"-isms have been removed?

**Comment by gertingold** [comment]
Given #247 and the discussion in #254, the original reasons for opening this issue have been addressed. This issue should not be showstopper for a new release. So I am closing it.

**Comment by GaelVaroquaux** [comment]
Great! This is what I thought. Thanks for confirming.
