### ISSUE TITLE
Modernize the scikit-learn chapter

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#245]
The scikit-learn chapter is really bad: it was written a very long time ago, when the project was young.

I give a course each year that fits in the time, and would be great material to integrate in the scipy-lectures. It is hosted as IPython notebooks:
https://github.com/GaelVaroquaux/sklearn_ensae_course

This would be a not too hard task, as it's mostly a question of changing the form of the material.

Note that, all figures must be generated from examples, hence a lot of the code should be converted to  examples.

**Comment by souravsingh** [comment]
@GaelVaroquaux I would like to take a stab at the issue.

**Comment by GaelVaroquaux** [comment]
Yey! That's great.

It should be somewhat straightforward. But somewhat only.

I am not sure what the best option is in terms of transforming the IPython notebooks. 

Quite clearly the first one should be turned into a rst document and a few examples to generate the figures (make sure that you understand well the generation of figures with sphinx-gallery). 

Similarly for the second one (skip the last 2 code cells). Notebook 01_... should be turned to a quick intro section that would go as the last section of the first chapter of the scipy-lectures and, inside the scikit-learn section, we would refer to it.

Notebook 03_... should probably be turned into a notebook-style example (see http://sphinx-gallery.readthedocs.io/en/latest/tutorials/index.html#notebook-examples).

I suggest that we first try to get these done, and go through a first iteration of reviewing and improving these. That way the process to get the others done will be more clear.

Also, don't hesitate to ask question at any time. Ideally pushing code in a WIP (work in progress) PR, to facilitate discussion. I'll try to be as reactive as possible.

Importantly, during the process, we should always add links to the other parts of the scipy-lectures, and to the relevant parts of the scikit-learn docs (and sometimes to wikipedia).

**Comment by GaelVaroquaux** [comment]
Implemented in #320 . Closing
