### ISSUE TITLE
Consistent Numpy/NumPy naming

### ISSUE THREAD

**Issue by btel** [scipy-lectures/scipy-lecture-notes#250]
In the lecture both NumPy and Numpy (lowercase or uppercase 'p') are used:

```
$ find . -name "*.rst" -exec grep Numpy -ow {} \; | wc -l
108
$ find . -name "*.rst" -exec grep NumPy -ow {} \; | wc -l
35
```

 It would be better to choose one and be consistent.

**Comment by GaelVaroquaux** [comment]
> It would be better to choose one and be consistent.

Agreed. What's the official spelling?

**Comment by emmanuelle** [comment]
I would say that it's NumPy, but even http://docs.scipy.org/doc/numpy/reference/ is not completely consistent: the first sentence is "This reference manual details functions, modules, and objects included in Numpy, describing what they are and what they do. For learning how to use NumPy, see also NumPy User Guide" so they are using the two different names in the two sentences!

**Comment by btel** [comment]
Thanks, @emmanuelle. I reported it back on numpy issue tracker: https://github.com/numpy/numpy/issues/7986

**Comment by vahtras** [comment]
PR merged. Closing.
