### ISSUE TITLE
Is 1-2 hours per chapter realistic?

### ISSUE THREAD

**Issue by moorepants** [scipy-lectures/scipy-lecture-notes#269]
On the main page it claims that the chapters correspond to a 1 to 2 hour course. Does this mean for live teaching or for private reading and working?

After checking out the first chapter, there seems to be way more material than could be covered in a 1 to 2 hour classroom session. Are the time estimates from previous teaching?

Not sure where else to ask this.

**Comment by GaelVaroquaux** [comment]
> Does this mean for live teaching or for private reading and working?

Live teaching.

> After checking out the first chapter, there seems to be way more material than
> could be covered in a 1 to 2 hour classroom session. Are the time estimates
> from previous teaching?

Estimates from previous teaching. That said, when I teach the first
chapter, I do tend to skip parts. We should find a way to indicate which
parts are "skippable". Any suggestion on a good formulation to indicate
that?

**Comment by moorepants** [comment]
Ok, that sounds good.

SWC introduced timings for each section of their lessons recently. It'd be nice if we had section level timings listed for these lessons. I think it would be up to the instructor to decide what they want to skip. It'd be helpful to know whether future topics depend on each section. With timings and dependencies listed it would become quite easy to modularize the lessons and simply pick and choose what you want to deliver.
