### ISSUE TITLE
Color printing

### ISSUE THREAD

**Issue by MySchizoBuddy** [scipy-lectures/scipy-lecture-notes#27]
I understand this has to be a printed in color cause of the images but there is lot of other colors like every single code has a color background. That is an awful lot of color to print and gain nothing. Can you create a version where the code background isn't colored. Perhaps add a border around the code to differentiate them. Color printing is expensive. I would prefer to use color ONLY where it is absolutely necessary like the color images

**Comment by pdebuyl** [comment]
The background was dimmed strongly in 2015 and is about 97% white now. If the current release of the lecture notes still have a problem, please open a new issue.
