### ISSUE TITLE
Expose each gallery as a "code sample" section, at the end of each chapter

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#270]
For each chapter with an example/auto_example gallery, we should include it at the end of the chapter the corresponding gallery. Examples in the current master are for the matplotlib chapter, or the statistics chapter.

Things to keep in mind are that it should slot in as well as possible in the table of content. For this, we can play with either a toctree to include it (as in the matplotlib chapter), or the include directive (as in the statistics chapter). Also, what we put in the README.txt, used by sphinx-gallery to create the gallery, is important.

**Comment by GaelVaroquaux** [comment]
If people want to pick this up, this is done in the packages/statistics.index.rst file and in the intro/scipy.rst. These files can serve as examples.

**Comment by gertingold** [comment]
I will work on it.

**Comment by GaelVaroquaux** [comment]
Closing as implemented by #316. Thanks @gertingold !
