### ISSUE TITLE
'in-place operation' code example obsolete?

### ISSUE THREAD

**Issue by zpz** [scipy-lectures/scipy-lecture-notes#278]
2.2.1.4.6. Example: inplace operations (caveat emptor)

The example regarding

  x -= x.transpose()

shows correct result, without the in-place modification effect showcased in the sample.

I'm using Python 3.5.2, numpy 1.11.3

**Comment by pdebuyl** [comment]
I needed to go as far back as NumPy 1.5 to find this erroneous behavior. NumPy 1.5 dates from 2010. I guess that we can drop the example? I ping @khinsen for his documentation on API changes :-)

Unless I receive some negative feedback (a solution might be to point out that for 10 year old numpy you should be aware of that) I'll close "as is".

**Comment by pdebuyl** [comment]
BTW: Yay for anaconda.

```
conda create -n old_numpy_env
conda activate old_numpy_env
conda install numpy=1.5
```

**Comment by gertingold** [comment]
+1 for dropping the example. I do not think that we should confuse people with versions of NumPy that old.

**Comment by khinsen** [comment]
@pdebuyl Thanks for the ping :-)  That change caused me quite some trouble at the time, so I won't forget it. But the lectures should certainly not cover remote history. The present is tough enough as it is ;-)
