### ISSUE TITLE
'block of memory' code example obsolete?

### ISSUE THREAD

**Issue by zpz** [scipy-lectures/scipy-lecture-notes#279]
2.2.1.2. Block of memory

the example in my machine prints out differently:

In [256]: x = np.array([1,2,3], dtype=np.int32)

In [257]: x.data
Out[257]: <memory at 0x7f16471847c8>

In [258]: str(x.data)
Out[258]: '<memory at 0x7f1647184888>'

I'm using Python 3.5.2, bumpy 1.11.3

To get the print-out in the notes, I needed to use 'tobytes':

In [259]: x.tobytes()
Out[259]: b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

**Comment by pdebuyl** [comment]
Hi @zpz thank you for the report.

`bytes(x.data)` seems to work properly across the Python2/3 gap, I will try it instead.

**Comment by pdebuyl** [comment]
I actually fixed this some time ago, closing. The current version works as advertised using "bytes".
