### ISSUE TITLE
matplotlib tutorial: examples not showing

### ISSUE THREAD

**Issue by amueller** [scipy-lectures/scipy-lecture-notes#281]
here:
http://www.scipy-lectures.org/intro/matplotlib/matplotlib.html#other-types-of-plots-examples-and-exercises

![image](https://cloud.githubusercontent.com/assets/449558/24973542/292f2420-1f8d-11e7-8d52-69df776ce9ef.png)

I don't think that's intentional.

**Comment by pdebuyl** [comment]
A "fresh" build does not do this. @GaelVaroquaux what is the procedure for re-building the website?

**Comment by pdebuyl** [comment]
solved by uploading a recent version
