### ISSUE TITLE
matplotlib tutorial: "edit" link dead

### ISSUE THREAD

**Issue by amueller** [scipy-lectures/scipy-lecture-notes#282]
The edit link in the top right corner goes here:
https://github.com/scipy-lectures/scipy-lecture-notes/edit/master/intro/matplotlib/matplotlib.rst

which is 404

**Comment by amueller** [comment]
works now, now idea what changed. Thanks for checking :)

**Comment by GaelVaroquaux** [comment]
Pierre, you're awesome at fixing bugs!

**Comment by pdebuyl** [comment]
No problem, I come from time to time to check the issues here :-)
