### ISSUE TITLE
update matplotlib section

### ISSUE THREAD

**Issue by choldgraf** [scipy-lectures/scipy-lecture-notes#283]
First of all, these resources are **awesome**.

Secondly - I noticed that the matplotlib section could use some improvements. A few quick points:

1.  Are these examples using MPL 2.0? They should!
2. There should be the use of `plt.subplots` in there somewhere, as I feel like this is the most common axis creation step people take.
3. A lot of these links are gonna break soon as I'm updating the matplotlib API to use sphinx gallery + stub pages instead of having one gigantic pyplot page like there is now.
4. Is there any plan to use sphinx-gallery to generate the files etc for these materials instead of having them hard-coded as RST? Might be a useful upgrade so users could download, e.g., jupyter notebooks of each lesson.

I've gotta focus my effort on getting this MPL sphinx-gallery pull request merged, but after this I can spend some time to try and improve these materials. Just putting this out there to see what folks think about it since I have matplotlib on the mind right now :)

**Comment by rougier** [comment]
1. Not, I made them using pre-2.0 version.
2. I tend to stick to `plt.subplot` but you're right an example using `plt.subplots` would be a great adition
3. That's great news. Could drop us a message when you'll push the change ?
4. Not sure about plan on that.

**Comment by krother** [comment]
I just did a few of the exercises to test them for my students. The material is generally awesome. I was a bit surprised that some figures (quiver) look different on matplotlib 2.0.2.
Are you interested in updating the dependency, as it would improve plot quality in some cases and make adoption easier?

I am aware that this would require checking through 100+ auto-generated plots manually. I would be interested to actually do that.

**Comment by rougier** [comment]
That would be awesome! This chapter needs to be updated but I do not have much time right now. But I should be able to review the PR.

**Comment by krother** [comment]
I got the development system running and updated figures in the NumPy and matplotlib chapters. The dev branch is here: https://github.com/krother/scipy-lecture-notes/tree/matplotlib2/intro Will let you know when I'm done with the rest.

**Comment by pdebuyl** [comment]
Hi all,

I merged a matplotlib 2.2 compatible branch today. I had to update some other packages to match the version requirements.

I propose to publish the current state as 2019.1.

I did a bit of "ménage" in the opened PR and this should be an improvement already. Then, we should update all packages to less outdated versions.

**Comment by pdebuyl** [comment]
Hi @scipy-lectures/developers @choldgraf 

The current version works fine with matplotlib 2 and 3.

The main tutorial relies on code that is not executed during the tests but the examples linked are all autogenerated at build time so it is not that bad. I tested the narrative examples from the tutorial.

The major step of updating the code is ok from my point of view but we would need a auto-tested tutorial for the future.

Feedback?

**Comment by GaelVaroquaux** [comment]
I agree that auto-tested tutorial would be better.

One option would be to rely on "notebook-style" source code for
sphinx-gallery
https://sphinx-gallery.github.io/stable/tutorials/index.html
and turn the whole tutorial into one of them.

**Comment by choldgraf** [comment]
Agreed!

A similar option is to use something like [jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx) which will auto-execute code on the same page as a part of running the docs

**Comment by GaelVaroquaux** [comment]
> A similar option is to use something like jupyter-sphinx which will auto-execute code on the same page as a part of running the docs

Is the source the sphinx code, or .ipynb files?

**Comment by choldgraf** [comment]
the sphinx code - basically, it just gives you a directive like so:

```
.. jupyter-execute::

   print('some code')
```

And at build time, it collects each of these chunks, executes them w/ a jupyter kernel, and shows the outputs in-line.

**Comment by pdebuyl** [comment]
Does jupyter-sphinx provide testing against a reference output as well?

**Comment by choldgraf** [comment]
Huh, I don't believe so but that is kind of a clever idea, I wonder if it's possible to combine the outputs with pytest somehow. Maybe worth opening up an issue in the jupyter sphinx repo? I don't think a full testing framework makes sense but maybe it could be a quick check at the end of docs pages or something

**Comment by choldgraf** [comment]
Another option is that you could add a final call to jupyter-execute that runs several assert statements, and then hide it from the page output. Again it's definitely not a full test suite but could be a good way to probe the state of the kernel after running all the code on the page

**Comment by GaelVaroquaux** [comment]
Overall jupyter-sphinx seems like a cool idea.

The only thing that I worry about is the dependencies. The reason that I
worry about this is that updating or environment.yml is always a
nightmare as there are gridlocks of conflicting requirements. However,
the jupyter-sphinx requirements seem fairly mild, so it might be worth
giving it a spin.

A nice side effect would be that we could use it to activate Thebelab on
the scipy-lectures. This would be very cool and probably help us reach
our goal of being a good learning material.

**Comment by choldgraf** [comment]
for what it's worth, I think that jupyter-sphinx is planning to switch away from `nbconvert` (a heavier dependency) to `nbclient` soon (because execution functionality is being pulled out of nbconvert and into nbclient), which will be more lightweight.

Also, I see that there are options for both `hide-input` and `hide-output` here: https://jupyter-sphinx.readthedocs.io/en/latest/#directive-options so I wonder if another reasonable option would be `hide-cell`, or if both `hide-input` and `hide-output` can be used in tandem to effectively have "test directives"

**Comment by choldgraf** [comment]
also also, I wanna draw your attention to a (very, very young) project we are working on to improve writing computational documentation in Sphinx: 

* https://myst-parser.readthedocs.io/
* https://myst-nb.readthedocs.io/

It's two things: a first-class markdown parser for Sphinx, and a notebook parser for Sphinx. The second project (myst-nb) will also probably define some kind of "represent an executable notebook with pure markdown" structure, and may be of interest as well. A lot of that functionality will probably be upstreamed into `jupyter-sphinx`, and those projects are still to young to use in production, but just wanted to clue you into it in the meantime in case it's of interest.

**Comment by pdebuyl** [comment]
@choldgraf I was indeed thinking of running pytest on the outputs. This is what we do currently and it has some good features such as test modifiers (skip a test, compare numerical values instead of character-per-character comparison, ignore whitespace differences, ellipsis for varying outputs). We also have to consider the overall complexity of the stack.

We should probably start it as a test after the coming release.
