### ISSUE TITLE
move to scikit-image 0.12 for building?

### ISSUE THREAD

**Issue by emmanuelle** [scipy-lectures/scipy-lecture-notes#289]
Would it be possible to move to scikit-image 0.12 for building the website (in circle.yml)? 0.12 was released in March 2016 and is included in Ubuntu zesty (0.13 in arty). 

I'll take care of the modifications if everybody thinks we do this version bump.

**Comment by gertingold** [comment]
+1 The code examples contain deprecated code which is something we should avoid.

In this context, I am wondering whether we should set up a requirements file. In this way, it would be clear which versions of the packages the lecture notes are intended for and it would be easier to get rid of deprecation warnings and similar errors.

**Comment by GaelVaroquaux** [comment]
> +1 The code examples contain deprecated code which is something we should avoid.

+1.

> In this context, I am wondering whether we should set up a requirements
> file. In this way, it would be clear which versions of the packages the
> lecture notes are intended for and it would be easier to get rid of
> deprecation warnings and similar errors.

+1 Also, we could use this file in the CI configuration.

**Comment by GaelVaroquaux** [comment]
Tackled in #302

**Comment by pdebuyl** [comment]
Changing the deprecated filter `hsobel` to `sobel_h` makes it work with skimage 0.12 and 0.13.

If there is interest, the change is here: https://github.com/pdebuyl/scipy-lecture-notes/tree/fix_hsobel

**Comment by GaelVaroquaux** [comment]
@emmanuelle  @pdebuyl : the build system is now on skimage 0.12, and passing!

A PR to make the corresponding skimage more modern would be welcome.
