### ISSUE TITLE
Change the Sympy imports to not flatten the namespace

### ISSUE THREAD

**Issue by drvinceknight** [scipy-lectures/scipy-lecture-notes#297]
Currently at http://www.scipy-lectures.org/packages/sympy.html we are importing `sympy` as follows:

```python
from sympy import *
```

I suggest changing this to:

```python
import sympy as sym
```

This would require modifying various calls in the docs but otherwise making no other changes.

**Comment by pdebuyl** [comment]
Is `sym' a somewhat standard abreviation for sympy? `sympy` is short enough that it could left as is no?

**Comment by drvinceknight** [comment]
Sym is the recommended abbreviation (and also what I personally use in my teaching).

> is short enough that it could left as is no?

Leaving it as `sympy` is an option (just as long as `numpy` but the status quo is `from sympy import *` which I would suggest is not a good approach.

**Comment by drvinceknight** [comment]
I am happy to pick this up and open a PR. If it is preferred to not make the move or to change to anything else that can be closed/modified :)

**Comment by GaelVaroquaux** [comment]
> I am happy to pick this up and open a PR. If it is preferred to not
> make the move or to change to anything else that can be closed/modified
> :)

I have no string opinion on what the best practice is in terms of
shorthand for sympy. Should we simply ask the sympy developers?

**Comment by drvinceknight** [comment]
> Should we simply ask the sympy developers?

Sure I'll ask on twitter.

FWIW in https://books.google.de/books?id=nHDtDAAAQBAJ&pg=PA264&lpg=PA264&dq=sympy+as+sym+best+practice&source=bl&ots=ky-RFj96Rx&sig=qJP8-gx0Ro4F9hVGKaFehHUIXck&hl=en&sa=X&ved=0ahUKEwi9ibyn4IPWAhVC1RoKHfNvD74Q6AEISjAG#v=onepage&q=sympy%20as%20sym%20best%20practice&f=false it has `import sympy as sym`

**Comment by drvinceknight** [comment]
and this tweet (from sympy): https://twitter.com/SymPy/status/678954093914759168

**Comment by pdebuyl** [comment]
fair enough :-)

**Comment by drvinceknight** [comment]
Closed by #307
