### ISSUE TITLE
Move all "optimize.fmin" and "optimize.fmin_*" to the corresponding "optimize.minimize"

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#300]
scipy.optimize.minimize is a more modern interface and should be preferred to the corresponding optimize.fmin functions.

**Comment by michael-hartmann** [comment]
I will work on this :)

**Comment by michael-hartmann** [comment]
This issue may be closed.

**Comment by GaelVaroquaux** [comment]
Thanks!
