### ISSUE TITLE
Move circleCI to Python 3

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#301]
This needs #298 to be done first.

**Comment by souravsingh** [comment]
@GaelVaroquaux We only need to change the Miniconda version [here](https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/build_tools/install.sh#L39) for this to be fixed, correct?

**Comment by GaelVaroquaux** [comment]
Darn, I just noticed that #302 removed the control of the Python version from our build system. That needs to be fixed. Any takers?

**Comment by GaelVaroquaux** [comment]
I've add an issue for that: #325

**Comment by souravsingh** [comment]
@GaelVaroquaux I can work on #325

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux I can work on #325

Awesome!!! Thanks!

**Comment by pdebuyl** [comment]
Sorry, hadn't seen this prior to do my tests, see #328

**Comment by GaelVaroquaux** [comment]
Fixed by #332
