### ISSUE TITLE
Restore Python 3 in the build system

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#325]
Before #302, the build system would choose the Python version used from an environment variable, which was set in the build matrix of the CI.

However, when build_tools/install.sh was simplified, that feature was lost. Hence we lost the ability to have a build matrix on the Python version.

In our install.sh we probably need to add the Python version to the environment.yml, hence adapting the strategy prior to #302 to the current one.

Relevant discussion: #301

**Comment by pdebuyl** [comment]
See #328 

I added the environment variable `PYTHON_VERSION` to the script `requirements_to_environment.py` and `environment.yml` is now created at run time. Travis and circle-ci report successful builds.

**Comment by GaelVaroquaux** [comment]
This is fixed by #328 . Thanks @pdebuyl !
