### ISSUE TITLE
scikit-learn-logo.png missing

### ISSUE THREAD

**Issue by gertingold** [scipy-lectures/scipy-lecture-notes#333]
Line 9 `packages/scikit-learn/index.rst` refers to `images/scikit-learn-logo.png` which seems to be missing. Is it ok to get the image from the scikit-learn github repo? If yes, I can prepare a corresponding PR.

**Comment by GaelVaroquaux** [comment]
Yes it is. I can also add the file when I get home tonight. 

⁣Sent from my phone, please excuse typos and briefness​

**Comment by gertingold** [comment]
Ok.

**Comment by GaelVaroquaux** [comment]
Fixed in 08f3aaa3be71e3ab0515126adf9917eae7c5457a
