### ISSUE TITLE
Releasing soon

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#335]
Just a heads up that I think that we could do a release soon: we have a bunch of major improvements that were done lately.

Things to do:

* [x] Merge #334
* [x] Merge #332
* [x] Maybe switch CircleCI to Python 3 by default
* [x] Check that the PDF renders well

**Comment by gertingold** [comment]
Does the html build work for Python 3? I am encountering a problem which seems to be caused by the fact that `version`defined in `conf.py` is of type `bytes`. A call to `sub` fails in Python 3. That is why I wrote #334 for Python 2. If I am doing something wrong and the build works fine for everybody else, I would rewrite #334 to Python 3 before the release.

**Comment by pdebuyl** [comment]
The line

    version = p.stdout.read().strip().decode()

of `conf.py` succeeds on Python 2.7 and 3.5 on my computer. It is included in #332.

With this PR, I can build the html and run the tests for Python 2 and 3 as:

    make test
    make test PYTHON=python3

    make html
    make html PYTHON=python3

The directories `auto_examples` must be cleaned up after a `make html` at this point if you want to change the Python version however.

**Comment by gertingold** [comment]
Perfect. I did my test without #332, so that's why. I will update #334 to Python 3.

**Comment by GaelVaroquaux** [comment]
> Perfect. I did my test without #332, so that's why. I will update #334 to Python 3.

I am merging #332

**Comment by pdebuyl** [comment]
Cool :-) I'll be glad to see an updated version online.

Maybe a few extra checks can be done before release:
- [ ] Assess #243 
- [ ] Use matplotlib 2.0? Or at least check that matplotlib 2.0 builds the html correctly (I believe it does but I have tons of warnings).
- [ ] quick proofread of the build/contribute instructions? (I can do that).

**Comment by pdebuyl** [comment]
Also, any timeline for the release? 1 week / 2 weeks?

**Comment by GaelVaroquaux** [comment]
I fear that updating to matplotlib 2.0 will be a lot of work, because the implicit dependencies of conda will force us to update more packages, and hence work on the doctests again. I think that this is something that we could do in a later release.

With regards to timeline, I actually wanted to do it last week (as with the school year starting, those lecture notes are really useful, including to me :) ), but I got delayed.

**Comment by gertingold** [comment]
@pdebuyl: You offer above to proofread the build/contribute instructions. I certainly would appreciate it if you take a look at my new text (instructions for Debian/Ubuntu). Also, I wonder whether we should keep the requirements section and the section on Fedora. Both seem quite outdated or incomplete to me. Could my new text serve as a replacement?

**Comment by pdebuyl** [comment]
Will do this week.

**Comment by GaelVaroquaux** [comment]
I am giving a course tomorrow. Should I make a rush tonight and try to
release? I need to check the generated PDF, but I can do that tonight.

**Comment by gertingold** [comment]
Concerning the building instructions, I think that my text should be more or less fine. The requirements and the Fedora section do not really seem to be up-to-date. So, if somebody agrees with this view, I could do the required changes tonight. Otherwise, I do not think that the build/contribute instructions should be a show-stopper if you want to release tonight. After all, the instructions do not show up in the html and pdf builds, right?

**Comment by GaelVaroquaux** [comment]
With regards to the fedora section, I am not really qualified. I can have
a look later on. The question is: is it more useful to keep it, even
imperfect, or should we suppress it?

**Comment by gertingold** [comment]
The main problem with the Fedora section, in my opinion, is that it does not account for the concrete requirements which we define. But I do not mind to keep it. One possibility would be to shift it after the Debian/Ubuntu section. And in the requirements section, we could put our current requirements. But this requires to keep it up-to-date.

**Comment by GaelVaroquaux** [comment]
+1 for shifting after. We can also point to the requirements file,  saying that this is the one up to date. 

⁣Sent from my phone, please excuse typos and briefness​

**Comment by GaelVaroquaux** [comment]
OK, I've checked the PDF, it's OK. Python 3 build is OK, also, I'll try to release (though it's past bedtime)

**Comment by pdebuyl** [comment]
I appreciate your enthusiasm, but I'd like a review myself if possible of the build instructions? (and just check `conf.py` for deprecated lines. really old deprecations actually). Also, I don't know if it is too much to ask but even though I am not a chapter author I wouldn't mind appearing on the cover. (please forgive this momentary abuse of self).

**Comment by rougier** [comment]
I'll make a PR for the cover.

**Comment by GaelVaroquaux** [comment]
> I'll make a PR for the cover.

Thanks Nicolas! I was doing it, but it seems that you're faster.

I won't have time to merge and release this morning. I need to go and
give my course.

**Comment by pdebuyl** [comment]
Good good. I have a small update for `conf.py` and for `Makefile`. As a sanity check for the project, could I do the release?

**Comment by GaelVaroquaux** [comment]
> As a sanity check for the project, could I do the release?

No problem. I had started editing some files to prepare for the release.
I'll send a WIP that you can take over.

**Comment by pdebuyl** [comment]
@gertingold I actually don't have access to a Fedora machine. Nor do I want to setup a suitable VM. I propose to delete the Fedora instructions and to replace them with "generic" instructions using pip.

I don't like the "all to conda" approach on my laptop (disk space is actually limited) and use the Debian packages for almost everything with a bit of pip.

**Comment by GaelVaroquaux** [comment]
> I don't like the "all to conda" approach on my laptop (disk space is actually
> limited) and use the Debian packages for almost everything with a bit of pip.

I agree with you, but I found it impossible to have the right version of
all the packages like this.

For instance, for the release (where I really need the right set of
package), I do the build with conda.

**Comment by gertingold** [comment]
Replacing the Fedora instructions by "generic" pip instructions is fine with me. In fact, I am also still using virtual environments most of the time.

BTW, I am wondering whether the TeX dependencies which I have listed in the Debian/Ubuntu section are complete. LaTeX does not complain, but the output is not correct in some places. For example, around page 600, text is constrained to half the textwidth after a right aligned figure. I wonder whether this is due to a missing dependence or whether there is actually a problem. @GaelVaroquaux: did you notice such a problem when checking the pdf yesterday?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux: did you notice such a problem when checking the pdf yesterday?

I did. I know why it happens, but I am not sure how to address it.

**Comment by gertingold** [comment]
Neither do I. But then it is not due to LaTeX dependencies which I might have missed.

**Comment by pdebuyl** [comment]
Progress in
- #341 
- #343
- #344

**Comment by pdebuyl** [comment]
See #342 for the final steps of the release

**Comment by pdebuyl** [comment]
@GaelVaroquaux @gertingold the wrapfigure environment used in Sphinx's latex output is too fragile. StackExchange and the GitHub issues are full of this type of bug. The solution suggested in https://github.com/sphinx-doc/sphinx/issues/3289 and https://github.com/sphinx-doc/sphinx/issues/3701 is to suppress the action of wrapfigure as

    \renewenvironment{wrapfigure}[2]{\begin{figure}[H]}{\end{figure}}

(addedd in the preamble).

The output is much nicer! And of course the html output is unaffected.

If that suits you, I'll include before releasing.

**Comment by rougier** [comment]
Nice, I tried to build the PDF yesterday and saw the problem but did not find a way to fix it.

**Comment by gertingold** [comment]
+1 for adding this before the new release.
Great, this solution works fine as far as I can see.

**Comment by GaelVaroquaux** [comment]
If you've checked the PDF output and it's nicer, please do include it.

Thanks!
