### ISSUE TITLE
Add a "conda-html" target in the make file

### ISSUE THREAD

**Issue by GaelVaroquaux** [scipy-lectures/scipy-lecture-notes#340]
I was building this morning in a conda environment and I was thinking that there are a bit too many manual steps. 

I was wondering, how easy would it be to create a Makefile target that sets up the environment if it's not available,  switches to it,  and builds there?

**Comment by pdebuyl** [comment]
It would be annoying.

All of it should be contained in a single line in the makefile (with possible continuations via backslashes, of course) that

1. active the env
2. run "make html" there

Wouldn't a bash-type wrapper be simpler?

```
#!/bin/bash
source PATH/TO/CONDA_OR_VENV/bin/activate
shift
$@
```

?

For conda envs, I do as in venvs, which is simply call the regular make html or make test.

**Comment by pdebuyl** [comment]
Still experimental but `conda run -n testenv make html` does that. Provide you have the conda executable in your PATH of course.

Apparently `/full/path/conda run -n testenv make html` is sufficient, one less line to type :-)

**Comment by pdebuyl** [comment]
At least some makefile "trickery" is required to make this work.

One option:

    source /path/to/conda/bin/activate testenv && python -m pytest ...

this requires "SHELL := /bin/bash" in the makefile though and an additional rule "conda-test" or "test-conda" for it to work.

**Comment by pdebuyl** [comment]
@GaelVaroquaux I will close unless there is further interest (say in the coming days)
