### ISSUE TITLE
Part 1.5 about global minimum

### ISSUE THREAD

**Issue by bayjan** [scipy-lectures/scipy-lecture-notes#350]
On part 1.5 about global minimum, the `optimize.basinhopping(f, 0)` gives correct answer, but `optimize.basinhopping(f, 3)` gives the same minimum point as `optimize.minimize(f, 3`). My version of scipy is 0.19.1.
Actually it is described on the documentation of `optimize.basinhopping`
_For stochastic global optimization there is no way to determine if the true
global minimum has actually been found. Instead, as a consistency check,
the algorithm can be run from a number of different random starting points
to ensure the lowest minimum found in each example has converged to the
global minimum.  For this reason ``basinhopping`` will by default simply
run for the number of iterations ``niter`` and return the lowest minimum
found.  It is left to the user to ensure that this is in fact the global
minimum._
So, I think on scipy lecture notes a reader should be informed about this.
Thank you.

**Comment by GaelVaroquaux** [comment]
Do you want to right a very short text on this and submit a pull request
with a small "topic" directive in the right spot?

**Comment by bayjan** [comment]
Wow, thank you for your very quick reply. 
OK, I can do that, but documentation is pretty well-described. So, maybe a text I copied from the documentation can be put as a "Warning" or "Note".

**Comment by GaelVaroquaux** [comment]
A warning would be good. But we need to summarize more: scipy-lectures is
a condensed document, that's what people like about it.

**Comment by bayjan** [comment]
OK. So, here is my suggestion:

**Warning: `optimize.basinhopping` may not return the global minimum**
Try multiple starting points to find the global minimum. 
For example, in this case:
```
 >>> min([optimize.basinhopping(f,x0=x[i]).x for i in range(0,len(x),50)])
 array([-1.30644001])
```

**Comment by GaelVaroquaux** [comment]
This is great! Could you send a pull request. 

⁣Sent from my phone. Please forgive typos and briefness.​
