### ISSUE TITLE
Wrong code for example 2D arrays (such as images)

### ISSUE THREAD

**Issue by heyutu** [scipy-lectures/scipy-lecture-notes#358]
http://www.scipy-lectures.org/intro/numpy/array_object.html

In the section 1.3.1.4. Basic visualization, the code for example 2D arrays (such as images) is wrong, also wrong in the pdf version.
  
![image](https://user-images.githubusercontent.com/2776867/34675682-ad082f58-f48a-11e7-9503-902b579550ae.png)

**Comment by pdebuyl** [comment]
Hi @heyutu 

Thank you for raising the issue. I'll work on this soon.
