### ISSUE TITLE
Use a maintenance branch

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#359]
I propose to create a maintenance branch (2017.1.i) so that we can merge bugfix-type PRs that fix typos, rendering, etc.

We would use the master branch for developing 2018.x, for instance.

The website could be redeployed on minor releases, or even using a rolling release (2017.1.roll).

**Comment by pdebuyl** [comment]
@vahtras @gertingold @rougier @GaelVaroquaux @emmanuelle 

I think of updating the web version, like, in the coming hours. There have been only minor fixes (typos, small bugs, etc) since the release 2017.1 so I see nothing blocking an update.

For testing the build/upload process, I uploaded the pages to http://pdebuyl.be/tmp/sln/ (temporarily)

**Comment by pdebuyl** [comment]
BTW: the motivation is that some users report already fixed bugs.

**Comment by vahtras** [comment]
Go ahead!

**Comment by GaelVaroquaux** [comment]
> I think of updating the web version, like, in the coming hours. There
> have been only minor fixes (typos, small bugs, etc) since the release
> 2017.1 so I see nothing blocking an update.

Yes!! That's awesome. Thank you!

**Comment by pdebuyl** [comment]
Done yesterday evening. I propose to keep this issue open for communication purposes.
