### ISSUE TITLE
Incorrect code in 1.3.1.4. Basic visualization

### ISSUE THREAD

**Issue by pablogps** [scipy-lectures/scipy-lecture-notes#364]
The examples for 1D plotting and 2D plotting have the same code (which is right for the 1D example).

**Comment by pdebuyl** [comment]
Hi @pablogps 

Thank you for the feedback!

Can you please provide a link to the page (ideally a direct link to the subsection)? This will save us a lot of time in making sure that we address the issue you have observed.

**Comment by pablogps** [comment]
It would be here:

http://www.scipy-lectures.org/intro/numpy/array_object.html#basic-visualization

**Comment by pdebuyl** [comment]
Thank you for the update. We did fix the issue but did not update the online version to reflect the update. I will update the web version shortly and only close the issue then.

**Comment by pablogps** [comment]
Thank you, very efficient! :)
