### ISSUE TITLE
Incorrect figure in scikit-learn

### ISSUE THREAD

**Issue by pablogps** [scipy-lectures/scipy-lecture-notes#368]
In the scikit-learn chapter you introduce the concept of regularization. You show a comparison of a 4-degree and a 9-degree polynomial fit. Then ask, "which do you prefer? Let's see the ground truth" and repeat the same graph. I suppose you wanted here to show the error for each (which should be higher for the better choice, the 4-degree polynomial).

Link to the section:
http://www.scipy-lectures.org/packages/scikit-learn/index.html#regularization-what-it-is-and-why-it-is-necessary

**Comment by pdebuyl** [comment]
@GaelVaroquaux I believe you wrote that section.
