### ISSUE TITLE
minor mistake > 1.3.1.3. Basic data types > Strings: sample code (no need for "," at last)

### ISSUE THREAD

**Issue by yasokada** [scipy-lectures/scipy-lecture-notes#371]
At
https://www.scipy-lectures.org/intro/numpy/array_object.html#basic-data-types
Strings:

`py
f = np.array(['Bonjour', 'Hello', 'Hallo',])
`

Above sentence can run but it should better be below.

`py
f = np.array(['Bonjour', 'Hello', 'Hallo'])
`

**Comment by GaelVaroquaux** [comment]
Fixed by #389
