### ISSUE TITLE
Section 3.6.7.2. wrong labels in image

### ISSUE THREAD

**Issue by pablogps** [scipy-lectures/scipy-lecture-notes#373]
This section applies a SVM to classify face images. An image is created to show how well it did, including the predicted labels (black if right, red otherwise). These labels are incorrect (it is very easy to see that the faces don't match).

The label code is
`ax.set_title(faces.target[y_pred],
                 fontsize='small', color=color)`

but should be

`ax.set_title(y_pred, fontsize='small', color=color)`

**Comment by pdebuyl** [comment]
Finally took the care to check this. I am less familiar with the scikit-learn chapter, sorry for the delay. This is fixed in the upcoming PR #467
