### ISSUE TITLE
Mobile view shown from desktop/laptop

### ISSUE THREAD

**Issue by rnelsonchem** [scipy-lectures/scipy-lecture-notes#374]
When I navigate to the starting page from my laptop (Chrome, Windows PC), the text on the main page is huge. It seems like it might be showing a mobile view by default. I have to decrease the scaling to about 80% until the page looks normal. The site looks fine from my phone.

**Comment by rnelsonchem** [comment]
Update. On my work desktop, the site appears fine. Both my laptop and desktop are using the same version of Chrome (67.0.3396.87 64-bit official build). I've attached a non-zoomed in view of the site from my laptop computer below -- as you can see, the text is way too large. 

![image](https://user-images.githubusercontent.com/3750670/41556582-3c27e348-7309-11e8-8aae-1aab311abe84.png)

**Comment by pdebuyl** [comment]
Hi, under Chromium/Linux and Firefox/Linux i see a perfectly reasonable scale. We'll have to wait for confirmation by other users to confirm and/or investigate this issue.

**Comment by rnelsonchem** [comment]
Another data point... This may have something to do with screen resolution. I've tried this on two Win10 laptops with very high DPI screens (3200x1800), and both laptops show the same issue. The site displays fine on my work computer (1920x1080) or if I lower my laptop screen resolution to the same.

**Comment by pdebuyl** [comment]
Your problem might be related to #346 We'll leave them both open for now.

If anyone on the team has one of these high DPI displays, that'd be good.

@rnelsonchem do you know css?

**Comment by GaelVaroquaux** [comment]
I've submitted a PR that might fix this: #375.

Could people confirm / infirm?

**Comment by pdebuyl** [comment]
For test:
 - without the fix: http://pdebuyl.be/tmp/sln/
 - with the fix: http://pdebuyl.be/tmp/sln-retina/

**Comment by GaelVaroquaux** [comment]
If no one confirms / infirms that it helps, I would be in favor of merging the PR. It cleans up the CSS, so it shouldn't be bad in general.

**Comment by pdebuyl** [comment]
https://twitter.com/pdebuyl/status/1017346068583976961

I hope my web host won't crash :-)

**Comment by pdebuyl** [comment]
Ok, two votes in favor and zero against. Let's merge.

**Comment by GaelVaroquaux** [comment]
Should be fixed by #375
