### ISSUE TITLE
Error in section 1.2.2.2. Containers

### ISSUE THREAD

**Issue by bugalo** [scipy-lectures/scipy-lecture-notes#377]
I might have found an error in section "1.2.2.2. Containers", subsection "Strings". The first square shows the use of single, double and triple quotes, and the second square shows a syntax error. I understand that the second square is not supposed contain this error. 

You might consider to take advantage of this error, and explain here how to use " \' " in strings. If that was the original idea of the second square, then it needs some wording.

**Comment by gertingold** [comment]
Thank you for the remark. I prepared a pull request (#380) adding a brief explanation.
