### ISSUE TITLE
Typo in section 1.2.3.5. Advanced iteration

### ISSUE THREAD

**Issue by bugalo** [scipy-lectures/scipy-lecture-notes#378]
In section 1.2.3.5. Advanced iteration, subsection "Looping over a dictionary", in the note it reads:

Note: The ordering of a dictionary in random, ...

I understand the "in" should be changed to "is".

**Comment by gertingold** [comment]
Thanks for pointing out this typo. I have opened a pull request fixing it.

**Comment by pdebuyl** [comment]
No reason to leave this open.
