### ISSUE TITLE
Do a 2018 release

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#384]
We should do a release soon. This is mostly a bugfix release but if only for the update of the CSS it would be nice.

Please list below the issues that you consider important to address before the release.

For the timeline, releasing in advance of EuroSciPy 2018 woud be nice.

**Comment by gertingold** [comment]
I am not against a release before the EuroSciPy but if we will have a sprint at Trento, it might make more sense to do a release afterwards (or we release twice within a short period which IMO would not necessarily be a problem).

**Comment by gertingold** [comment]
This sounds strange to me. Do you understand this phenomenon? May be it is worth looking into in Trento?

**Comment by GaelVaroquaux** [comment]
> This sounds strange to me. Do you understand this phenomenon?

Git stores previous versions of things like images.

> May be it is worth looking into in Trento?

We can try doing magic to reset the history.

**Comment by gertingold** [comment]
You are of course right, I had misinterpreted the remark by @pdebuyl somewhat. We could rewrite history by removing commits. The question would be whether there are commits which should not be touched because they concern files which are not created from other sources under version control. The number of commits is still reasonable, so this could be done during the sprint tomorrow.

**Comment by GaelVaroquaux** [comment]
I believe that I have addressed the problem of the repo size, but I don't know how to check it.

**Comment by GaelVaroquaux** [comment]
I've fixed the CIs. I will release soon.

**Comment by gertingold** [comment]
In principle, I have also the numpy_indexing figure ready in a new version. However I can only do a PR once I am back home. So if you want to release this evening, go ahead. And congrats for the success with circle CI!

**Comment by GaelVaroquaux** [comment]
I just did a release (via my mobile phone, walking to the Trento station).

But maybe we can do another soon. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
OK, release done!

Closing.

**Comment by Marr11317** [comment]
The cover page still says 2017. Is it an error, does the website link still download the 2017 version?

**Comment by pdebuyl** [comment]
@Marr11317 The pdf is generated from the latest release (2018) but the cover image had not been updated. I will fix this for the next release.

Thanks for the feedback :-)
