### ISSUE TITLE
Add another alternative to i / o images

### ISSUE THREAD

**Issue by Sphinxs** [scipy-lectures/scipy-lecture-notes#385]
Please add more options of modules to make the i / o of images. Using `misc.imsave` ([Image manipulation and processing using Numpy and Scipy](http://www.scipy-lectures.org/advanced/image_processing/)) I couldn't save the images, I searched for another module and I found the [imageio](https://pypi.org/project/imageio/) module.

**Comment by GaelVaroquaux** [comment]
Can you do a pull request that adds a "topic" note on this, please? 

Thank you !

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by pdebuyl** [comment]
`misc.imsave` is even deprecated! https://docs.scipy.org/doc/scipy/reference/release.1.0.0.html?highlight=imsave#deprecated-features
