### ISSUE TITLE
Memory leak in Numpy C-API example

### ISSUE THREAD

**Issue by moble** [scipy-lectures/scipy-lecture-notes#402]
Following a [similar a report of a similar issue in my own code](https://github.com/moble/quaternion/issues/92), I found a very snippet of code [here in the scipy lectures](https://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#numpy-support) that's very close to my own (possibly because I stole mine from here???).  The example shows how to wrap the `cos` function so that it works with numpy arrays.

The problem is that there appears to be an extra `Py_INCREF(out_array)` statement just before the return.  This raises the reference count of `out_array` to 2 (as I've verified by printing out the `Py_REFCNT`).  If I then loop over many calls to `cos_module_np.cos_func_np`, I see the memory usage increase with time.  If I remove that INCREF statement, the memory usage stays constant over time.  My test script looks like this:

```python
import cos_module_np
import numpy as np
import os

print("PID:", os.getpid())

for i in range(10000):
    x = np.linspace(0, 2*np.pi, num=50000);
    y = cos_module_np.cos_func_np(x)
    z = x+y
```

I've tested it with a current version of numpy and both python 2.7 and 3.6.

*However*, I'm not making this into a PR because I'm not entirely sure if that's the correct solution.  When I do the analogous thing with my own code, I eventually get segfaults after ~100 iterations.  I don't see such segfaults with this code, but our codes really look the same fundamentally, so I'm wondering if this is the correct approach.

**Comment by seberg** [comment]
Random comment, I find that snippet a bit strange, because NpyIter has nice stuff to iterate both arrays at once, it will even allocate the out array for you if you want. Other then that, I do not see why the INCREF there is needed, I do think that `out_array` should be initialized to NULL probably to make the error path save. Anyway, would have to carefully check things as well to be sure.

**Comment by moble** [comment]
@seberg Would you say that the modern approach would basically follow [this example](https://www.numpy.org/devdocs/reference/c-api.iterator.html#simple-multi-iteration-example) from the numpy C-API docs?  The main changes I see would be (1) some obvious arg-handling stuff and (2) replacing
```C
memcpy(dst, src, itemsize);
```
in the inner loop with something more like
```C
*(double *) dst = cos(*(double *) src);
```
Does that sound right?

**Comment by seberg** [comment]
Yeah, sounds right. Should add at least `NPY_ITER_ZEROSIZE_OK`. Might also want to check the dtype is double I guess, which seems currently missing. Doubt the current code is even correct for complex input memory layout....

**Comment by pdebuyl** [comment]
+1 for a PR.

I would like to know whether `PyArray_NewLikeArray` returns an objects with a refcount of one already, in which case the bug is well identified.
