### ISSUE TITLE
BinderHub support

### ISSUE THREAD

**Issue by westurner** [scipy-lectures/scipy-lecture-notes#403]
BinderHub support would be helpful.

There's an environment.yml in this repo, but AFAICS the all of the .ipynb's are in one folder in a different repo ( https://github.com/scipy-lectures/scipy-lectures.github.com/tree/master/_downloads ) and they don't contain output?

Binder builds Docker containers with repo2docker:

- https://repo2docker.readthedocs.io/en/latest/config_files.html#config-files

https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/conf.py

- Generating from .ipynb with nbsphinx would be a different approach that would break source history: https://nbsphinx.readthedocs.io/en/latest/
- Generating .ipynbs from Markdown with jupytext would preserve editability, but lose the RST ``.. contents:`` directive: https://github.com/mwouts/jupytext

...

- It'd be much easier to browse the notebooks with nbviewer and binderhub if they weren't all in _downloads; IDK whether just next to the source rst would be better?
- It'd be much easier to browse the notebooks with nbviewer if they contained output
  - And maybe a %version_information or %watermark?
    - https://github.com/jrjohansson/version_information (has pretty LaTeX output)
    - https://github.com/rasbt/watermark
    - There's a programmatic way to add cells to notebooks:
      - https://stackoverflow.com/a/45672031/188833
- Link to BinderHub and/or nbviewer in the rendered RSTs would be useful

**Comment by westurner** [comment]
How and where are the .ipynb's built? https://github.com/matthew-brett/nb2plots ?

**Comment by GaelVaroquaux** [comment]
> Sphinx-gallery. Tight integration in sphinx is paramount.

By the sphinx, sphinx-gallery does provide integration with binder. I
think that we would welcome a pull-request to scipy-lecture to turn it
on. I must confess that I've seldom been very successful with binder;
probably because of the load on this service.

**Comment by westurner** [comment]
https://sphinx-gallery.readthedocs.io/en/latest/configuration.html#binder-links

bndr.it supports a BinderHub server url preference so that bndr.it
shortlinks open in the user's preferred binder instance. It'd be great to
add support for this extra level of indirection in sphinx-gallery.
https://bndr.it/b/settings

What would need to happen to keep the .ipynb files organized in the same
directory structure instead of (or in addition to?) all in /_downloads?

**Comment by GaelVaroquaux** [comment]
> It'd be great to add support for this extra level of indirection in
> sphinx-gallery. https://bndr.it/b/settings

Sounds like a good it. Do you want to open an issue in sphinx-gallery?

> What would need to happen to keep the .ipynb files organized in the same
> directory structure instead of (or in addition to?) all in /_downloads?

I think that this is the sort of thing that is controlled by sphinx. But
I don't know how to do this, or whether it is possible. One would have to
ask a sphinx guru.
