### ISSUE TITLE
link to PDF files are stale on landing page: https://scipy-lectures.org/

### ISSUE THREAD

**Issue by thezedd** [scipy-lectures/scipy-lecture-notes#419]
the pdf links in "Download" side panel on the right reflect 2017.1 while the latest version is 2018.1

https://scipy-lectures.org/_downloads/ScipyLectures.pdf
https://scipy-lectures.org/_downloads/ScipyLectures-simple.pdf

**Comment by pdebuyl** [comment]
Hi,

We are aware of the problem. The pdf for the cover page was not updated for the release but the chapters match the 2018.1 release.

Thank you for the note, it is time that we do an update of the web content.
