### ISSUE TITLE
Can I add new third package which called GetFEM++?

### ISSUE THREAD

**Issue by tkoyama010** [scipy-lectures/scipy-lecture-notes#428]
Hello. Thank you for a good documentation for learning  scientific Python ecosystem.
I want to add a new third-party library python-getfem++ which is the library of Finite Element Method.

> GetFEM++ is an open source library based on collaborative development. It aims to offer the most flexible framework for solving potentially coupled systems of linear and nonlinear partial differential equations with the finite element method. GetFEM++ is interfaced with some script languages (Python, Scilab and Matlab) so that almost all of the functionalities can be used just writing scripts. 
http://getfem.org/

Although it is a library of C++. Most user uses it in python interface. I think that describing this library is in line with the spirit of this document.
Could you give me a opinion?

**Comment by pdebuyl** [comment]
Hi @tkoyama010 

Thank you for your interest in this project.

Our aim is to provide supporting material for the Python language, the foundational numerical packages (NumPy, SciPy, matplotlib), and for a selection of very widely used packages (such as sympy as scikit-learn).

Having a chapter on GetFEM++ is, at least in the near future, is out of the cope of the lecture notes. I'll leave the issue open for a week or so, in case another of the editors wants to comment as well.

**Comment by tkoyama010** [comment]
@pdebuyl Thank you for your comment.

> and for a selection of very widely used packages

I agree.

>  I'll leave the issue open for a week or so, in case another of the editors wants to comment as well.

Thank you.
