### ISSUE TITLE
typo in 1.3.3.2. Structured data types / Fancy indexing

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#430]
In section 1.3.3.2. Structured data types / "Fancy indexing works, as usual", the line samples[samples['sensor_code'] == 'ALFA'] return an empty array, it should read samples[samples['sensor_code'] == b'ALFA'] to return the expected array([(b'ALFA', 1. , 0.37), (b'ALFA', 1.5, 0.37), (b'ALFA', 3. , 0.11)], dtype=[('sensor_code', 'S4'), ('position', '<f8'), ('value', '<f8')])

**Comment by pdebuyl** [comment]
Thank you for the feedback, I fixed it in the current code (not on the web yet).

This is an annoying change between python 2 and 3.
