### ISSUE TITLE
simplify section 1.3.4.1. Polynomials example code

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#431]
In section 1.3.4.1. Polynomials, the "t = np.linspace(0, 1, 200)" line is actually misleading for a newbie (like me), it could be removed and the plotting could simply be "plt.plot(x, y, 'o', x, p(x), '-')".

**Comment by mcorne** [comment]
Same thing with section 1.3.4.1. Polynomials / "More polynomials (with more bases)".
Also, plotting all in one line "plt.plot(x, y, 'r.', x, p(x), 'k-', lw=3)" is easier for inline plotting.

**Comment by pdebuyl** [comment]
Hi @mcorne,

Thank you for the feedback. We often use a larger number of numerical points for plotting analytic functions to have a smooth rendering, which is why the example uses that.

A comment on the line

    t = np.linspace(0, 1, 200)

such as

    t = np.linspace(0, 1, 200) # use a larger number of points for plotting

would make it less confusing. What do you think?

**Comment by mcorne** [comment]
I see your point. I guess the comment would help. You may want to be a bit more specific as you explained it actually, eg "# use a larger number of points for smoother plotting".
Anyway, I would still drop the line at least in one of the examples because it does not make any difference as far as plotting in this case, and it is somewhat misleading as I thought for a sec that I could not use "x" more than once as an argument.

**Comment by pdebuyl** [comment]
I removed the extra definitions for the Chebyshev fitting as they were useless there. I added the comment with your improvement.
