### ISSUE TITLE
no solution in section 1.3.5.1. Array manipulations

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#432]
There is no solution for the 3 exercises in section 1.3.5.1. Array manipulations, contrary to the other sections. That would be nice to add the corresponding "Python source file". Feel free to use what I came up with below.
``` python
import numpy as np

# Example 1
a = np.arange(5) + 1
a[:, np.newaxis] + np.array([0, 5, 10])

# Example 2
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])
a / b[:, np.newaxis]

# Example 3
a = np.random.rand(10, 3)
b = np.abs(a - 0.5)
c = b.argsort(axis=1)[:, 0]
a[np.arange(10), c]
```

**Comment by pdebuyl** [comment]
Hi @mcorne

Thank you for your proposal. We leave intentionally such work "left to the reader as an exercise".
