### ISSUE TITLE
State objectives and design choices

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#434]
To @scipy-lectures/core 

I write below a suggestion that could go into "About -> contributing". Then, we would have a few guidelines to help in accepting or not some of the contributions.

Objectives:
- Provide a self-contained introduction to Python and its foundational computational packages (the "SciPy stack").
- Where possible, use automated testing of the code examples.
- Provide an introduction to a selection of computational libraries. Currently: pandas, statsmodels, seaborn, scikit-image, scikit-learn, sympy, and mayavi.

Design choices:
- Consider the chapters as a useful base for tutorials.
- Write readable code.
- Follow an idiomatic style (i.e. `import numpy as np`, prefer array operations).

**Comment by GaelVaroquaux** [comment]
I think that this is awesome, super useful, and summarizes well our
vision.

Thank you!!!

**Comment by gertingold** [comment]
An implementation is proposed in #457. Therefore, I am closing the issue which can of course be reopened if further discussion is needed.
