### ISSUE TITLE
wrong origin when plotting the 2D projection

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#438]
In the "2-D minimization" exercise in section "1.5.5.2. Finding the minimum of a scalar function", the origin should be set to "lower" when plotting the 2D projection (for both lines 27 and 53):
plt.imshow(sixhump([xg, yg]), extent=[-2, 2, -1, 1], origin='lower')

**Comment by gertingold** [comment]
Thanks for pointing out this problem.
