### ISSUE TITLE
use of deprecated normed arg instead of density to generate histogram

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#439]
In section "1.5.6.1. Distributions: histogram and probability density function", normed=True should be replaced by density=True since "normed" is deprecated.
histogram = np.histogram(samples, bins=bins, density=True)[0]

Same issue in "1.5.12.7. Normal distribution: histogram and PDF".

**Comment by gertingold** [comment]
Thanks for pointing this out. #445 fixes the deprecated keyword argument.

**Comment by pdebuyl** [comment]
And #445 is merged :-)
