### ISSUE TITLE
factor 2 missing in calc_deri() callback

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#440]
In section "1.5.7.2. Integrating differential equations", a factor 2 is missing in the derivative calculation of the damped spring-mass oscillator exercise, calc_deri() should return:
return (yvec[1], -2 * eps * omega * yvec[1] - omega **2 * yvec[0])
instead of
return (yvec[1], -eps * omega * yvec[1] - omega **2 * yvec[0])

Same issue in "1.5.12.6. Integrate the Damped spring-mass oscillator".

**Comment by gertingold** [comment]
Thanks for pointing out this mistake. It was fixed in #442 in the meantime.
