### ISSUE TITLE
broken links in wind spring prediction page and unused code

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#444]
Links to the "Solution: Python source file" are broken in section "1.5.11.1. Maximum wind speed prediction at the Sprogø station". Each 3 links should point to the corresponding file in "intro/summary-exercises/examples".

plot_sprog_annual_maxima.py should only have the following code:
```python
import numpy as np
from scipy.interpolate import UnivariateSpline
import matplotlib.pyplot as plt

years_nb = 21
wspeeds = np.load('sprog-windspeeds.npy')
max_speeds = np.array([arr.max() for arr in np.array_split(wspeeds, years_nb)])

plt.figure()
plt.bar(np.arange(years_nb) + 1, max_speeds)
plt.axis('tight')
plt.xlabel('Year')
plt.ylabel('Annual wind speed maxima [$m/s$]')
```

**Comment by gertingold** [comment]
The problem of broken links is not only present in section 1.5.11.1 but also in other sections like 2.6.2.

**Comment by pdebuyl** [comment]
Hi @mcorne thank you for the feedback, I fixed the links and deleted the dead code. This will show up in the upcoming release.
