### ISSUE TITLE
typo in Mini-exercise: data re-interpretation solution

### ISSUE THREAD

**Issue by mcorne** [scipy-lectures/scipy-lecture-notes#446]
In section "2.2.1.3. Data types", the the trailing [:, :, 0] should be removed from the solution that is simply: y = x.view([('r', 'i1'), ('g', 'i1'), ('b', 'i1'), ('a', 'i1')]).

**Comment by gertingold** [comment]
Omitting the trailing `[:, :, 0]` would yield an array of shape `(10, 10, 1)`. As far as I understand, the exercise asks for a shape `(10, 10)`. Therefore, I think that `[:, :, 0]` should be kept. Do you agree?

**Comment by pdebuyl** [comment]
I confirm @gertingold 's interpretation. From a few tests, it seems that view maintains the rank of ndarrays, which is why the trailing dimension remains.

**Comment by pdebuyl** [comment]
Unless someone has a proposal to improve the explanations, I will close this.
