### ISSUE TITLE
Floating Table of Contents Overlapping with Content

### ISSUE THREAD

**Issue by lucyturn3r** [scipy-lectures/scipy-lecture-notes#447]
As shown in the image attached the floating table of contents overlaps with the actual content of the page. This image was taken on a Surface Pro 4 using Google Chrome at 100% zoom. Changing the size of this floating menu or adding a way for the menu to be collapsed would be helpful.

![image](https://user-images.githubusercontent.com/27177303/61418130-a2c66e00-a94d-11e9-9db0-a0473e5dbfe9.png)

**Comment by pdebuyl** [comment]
Hi @lucyturn3r,

Thank you for the feedback. Testing with variable browser sizes, I could reproduce this as well.

This is a corner case of the css rendering, which we adjust depending on our own experience and on your feedback. I will look for a way to toggle it off by the user (javascript programmers welcome here).

**Comment by GaelVaroquaux** [comment]
> I will look for a way to toggle it off by the user (javascript
> programmers welcome here).

I would rather explore css media selectors rather than javascript.

**Comment by pdebuyl** [comment]
Do you mean the automatic settings depending on the display width?

In my test, the result was good with firefox and with chrome *without device simulation* but erroneous (as in the issue) with device simulation, suggesting that the media selector might fail here.

**Comment by GaelVaroquaux** [comment]
> Do you mean the automatic settings depending on the display width?

Fixing our CSS with the right media rules
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

> In my test, the result was good with firefox and with chrome without device
> simulation but erroneous (as in the issue) with device simulation, suggesting
> that the media selector might fail here.

No. Rather that our rules are incorrect.

**Comment by pdebuyl** [comment]
Can't reproduce anymore. In either the device simulator of chromium or in chrome/firefox all is fine.
