### ISSUE TITLE
Broken link to flymake

### ISSUE THREAD

**Issue by gertingold** [scipy-lectures/scipy-lecture-notes#452]
In `advanced/debugging/index.rst:159` the link to `flymake` is broken. Would https://www.emacswiki.org/emacs/FlyMake be a good replacement?

According to https://www.emacswiki.org/emacs?action=browse;oldid=PythonMode;id=PythonProgrammingInEmacs#toc17, `flymake` should work out of the box. Therefore, I am not sure whether the instructions given in the lecture notes are still valid. May be somebody proficient in Emacs could take a look at it.

**Comment by pdebuyl** [comment]
flymake does work out of the box, I use emacs and verified. according to the info on emacswiki it is only that simple since emacs 26 (may 2018). I will submit a PR with up to date instructions and info on emacs 26.
