### ISSUE TITLE
Add section on Python 2 / 3

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#463]
Python 2 becoming unsupported, I propose that we add a section on the whole Python 2 / 3 issue.

We should not patronize users. I propose to remain factual, pragmatic, and helpful.

- What is the transition from Python 2 to Python 3?
- How does it impact the usability of Python for science?
- Agenda of the migration: many packages are dropping support for Python 2 in coming releases.

We should probably release a version (or all 2020 releases if several) of the notes with Python 2/3 compatibility and  let it be available by some means as a maintenance branch (only bug fixes).

**Comment by GaelVaroquaux** [comment]
Absolutely! Thank you for raising this issue!

**Comment by vahtras** [comment]
Allow me to disagree. It is fine to have a historical note on the 2-3 transition now that it is 2020,  but I do not find a reason to have the notes 2/3 compatible anymore, as many major libraries already have dropped Python2 support.
My humble opinion,
Olav

**Comment by StevenLi-DS** [comment]
I think the following link might be helpful for the readers.
https://python3statement.org/

**Comment by pdebuyl** [comment]
@vahtras There are very few Python 2 incompatibilities in the current version. We can state that most of "2020.1" is Python 2 compatible and that's it. What do you think? Even though Python 3 is (or should be) the default by now, many scientists are barely aware of the change and Python 3 proselytism (or whatever you call) led to many negative discussions online (as far as I can tell). We already inform the readers of the deprecation of Python 2. I agree that there should be no more effort toward Python 2.

@StevenLi-DS thank you for the link. It is part of the section that I am preparing.

**Comment by StevenLi-DS** [comment]
@pdebuyl I actually read some recent python textbooks that claims Python 2 is still widely used. However, it's not the case for neither developers nor quant folks based on the following surveys.

https://www.jetbrains.com/lp/devecosystem-2019/python/
https://dev.pandas.io/pandas-blog/2019-pandas-user-survey.html

In fact, I think it might be worth mentioning the different between python 3.6 and other older versions due to the implement of f-string.

**Comment by pdebuyl** [comment]
@scipy-lectures/developers feedback welcome on the pull request https://github.com/scipy-lectures/scipy-lecture-notes/pull/475/files
