### ISSUE TITLE
update package version for build

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#464]
Local builds of the current notes is becoming difficult due to outdated packages.

Before the next release, we should make sure that we can build somewhere else than on travis or in a container.

**Comment by pdebuyl** [comment]
Related: updating pytest to ">=5.1" enables us to use the option "NUMBER" https://docs.pytest.org/en/latest/doctest.html#using-doctest-options

pytest does not cause regressions in general, so I'd like to update it and to create a pytest.ini file at the root of the repo with content

    [pytest]
    doctest_optionflags = NUMBER NORMALIZE_WHITESPACE

**Comment by GaelVaroquaux** [comment]
> pytest does not cause regressions in general, so I'd like to update it and to create a pytest.ini file at the root of the repo with content

I would suggest that you go ahead and do a PR, to see if tests pass.

Thanks!

**Comment by pdebuyl** [comment]
The tests run automatically on the branches in my fork (yeah for jargon!), see https://github.com/pdebuyl/scipy-lecture-notes/tree/test_number_options

Now: no error, only warning. This includes many deprecation warnings, some future deprecation and some runtime warnings.

The biggest change was the numpy printing! Also, finding an installable mix of versions was a bit annoying. I suggest we make a bigger update after the release.

**Comment by pdebuyl** [comment]
Note: the branch there can't be updated to Python 3.7 yet because there are no SciPy wheels for 0.19 / Python 3.7

**Comment by pdebuyl** [comment]
closed by #467
