### ISSUE TITLE
conda can't create env

### ISSUE THREAD

**Issue by TejasAvinashShetty** [scipy-lectures/scipy-lecture-notes#468]
I tried to build the conda env using the [contributing guidelines](https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/CONTRIBUTING.rst)

conda env create -f environment.yml 
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - coverage=4.4.1
  - sympy=1.0
  - scikit-learn=0.18
  - seaborn=0.7
  - matplotlib=1.5

**Comment by pdebuyl** [comment]
currently, our collection of packages is found for Python 3.6, which version are you using? We plan on updating the versions soon but will first release a first 2020 version of the notes.

**Comment by TejasAvinashShetty** [comment]
3,8
Regards,

Tejas Shetty
B Tech.Pharma
Department of Pharmaceutical Science and Technology
Institute of Chemical Technology, Matunga,
Maharashtra, India.
Contact No.: +91 9987015305,9004350057,8450978380,022 25582905
Email ID: tejasshetty.1808@gmail.com

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/19/20,
05:08:40 PM

**Comment by pdebuyl** [comment]
With conda, it is quite easy to achieve a python 3.6 install then.

    conda deactivate
    conda env remove testenv
    conda env create -f environment.yml python=3.6
    conda activate testenv

should work, let me know if that works for you.

**Comment by pdebuyl** [comment]
Hi @TejasAvinashShetty 

Did it work in the end? If so, please close the issue.

**Comment by TejasAvinashShetty** [comment]
yes
