### ISSUE TITLE
Release 2020.1

### ISSUE THREAD

**Issue by pdebuyl** [scipy-lectures/scipy-lecture-notes#472]
- [x] #453 
- [ ] #283 
- [x] #463 
- [x] check the release notes
- [x] update the release info in conf.py
- [ ] publish on zenodo (to discuss?)

@GaelVaroquaux @vahtras @emmanuelle

**Comment by pdebuyl** [comment]
@GaelVaroquaux I believe that you did the zenodo archives. I'd like to put the output of the notes on zenodo on top of / in place of the code. The html file and the pdf. This could become a citable resource more easily (not that citation is a goal of the lecture notes, but I think it would fair and nice to have them exist a bit like a book for citations). Thoughts?

**Comment by pdebuyl** [comment]
@GaelVaroquaux 

I updated everything. I believe a fuller review of matplotlib is needed but that we should publish 2020.1 anyway.

Can you push the release to zenodo? I'll update the website.

1. use `make zip`
2. create release on github
3. add the files scipy_lecture_notes.zip  ScipyLectures.pdf to the release on GitHub
4. push the release to zenodo

This way, the zenodo archive contains the rendered lectures.

I set the zenodo doi to the "master doi" in the files. I don't know if we can reserve a doi (which would enable us to put the current doi instead) and use the github/zenodo integration at the same time.

**Comment by pdebuyl** [comment]
@GaelVaroquaux I have done 1, 2, and 3. I cannot do 4 as it probably goes to your zenodo user, could you check? Or go to Zenodo, disable the github integration, so I'll enable it for my account.

**Comment by pdebuyl** [comment]
Release 2020.1 is live. Only missing item is zenodo upload, I leave the issue here open until that is done (btw, I understand that priorities may be shifted entirely for many of us -> no worry about that).

**Comment by pdebuyl** [comment]
For info (and my own memory), https://o2r.info/2019/02/24/archiving-jekyll-zenodo/

**Comment by mdhaber** [comment]
@jarrodmillman I think this can be closed.
