### ISSUE TITLE
Images links broken in mathematical_optimization/index.rst 

### ISSUE THREAD

**Issue by johntiger1** [scipy-lectures/scipy-lecture-notes#476]
Image links seem broken here: 

https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/advanced/mathematical_optimization/index.rst

For instance:
in https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/advanced/mathematical_optimization/index.rst#gradient-based-methods, there is a link to an image at 
`https://github.com/scipy-lectures/scipy-lecture-notes/blob/master/advanced/mathematical_optimization/auto_examples/images/sphx_glr_plot_gradient_descent_103.png`

**Comment by pdebuyl** [comment]
Hi @johntiger1 thank you for the feedback. Are you looking at the pages on github or on our website?

On the website, I see the image properly, see http://scipy-lectures.org/advanced/mathematical_optimization/index.html#gradient-based-methods

**Comment by johntiger1** [comment]
Ah, I am viewing it on the github, that's why. It works fine on the website

**Comment by pdebuyl** [comment]
ok, thanks for closing.
