### ISSUE TITLE
SVD s and sigmal remains 1S

### ISSUE THREAD

**Issue by elwolv** [scipy-lectures/scipy-lecture-notes#477]
numpy doc example for SVD  conversion of s to sigma to allow (sigma @ Vt) multiply does not work as s and sigma remains as 1D (728)

**Comment by pdebuyl** [comment]
Hello, thank you for the feedback. Can you provide a direct link to the relevant page of our website http://scipy-lectures.org/ ?

**Comment by elwolv** [comment]
hello


thank you for your respond

enclosed a word file with the contents I tried and did not work
{https://numpy.org/devdocs/user/tutorial-svd.html}

this the web page I used.
after that I used scipy web page 
{https://scipy-lectures.org/}
and this did work fine, but I wanted to get the example in numpy to work on the
image for demo purpose/

thank you for your help

**Comment by pdebuyl** [comment]
The web page at https://numpy.org/devdocs/user/tutorial-svd.html belongs to the NumPy project. If you need assistance with NumPy, you can try stackoverflow https://stackoverflow.com/questions/tagged/numpy or the NumPy mailing list https://mail.python.org/mailman/listinfo/numpy-discussion

Apart if there is a specific issue with the document that we manage, I will close the issue.
