### ISSUE TITLE
Warning running plot_mandelbrot.py

### ISSUE THREAD

**Issue by biniek** [scipy-lectures/scipy-lecture-notes#480]
When I try to run 
scipy-lecture-notes/intro/numpy/examples/plot_mandelbrot.py /
I get following warning:

"Warning (from warnings module):
  File "C:\Users\biniek\Desktop\plot_mandelbrot.py", line 23
    z = z**2 + c
RuntimeWarning: overflow encountered in square

Warning (from warnings module):
  File "C:\Users\biniek\Desktop\plot_mandelbrot.py", line 23
    z = z**2 + c
RuntimeWarning: invalid value encountered in square

Warning (from warnings module):
  File "C:\Users\biniek\Desktop\plot_mandelbrot.py", line 25
    mandelbrot_set = (abs(z) < some_threshold)
RuntimeWarning: invalid value encountered in less"

Am I doing something wrong or is there something wrong with the code?
Thank you!

**Comment by pdebuyl** [comment]
Hello,

Thank you for the feedback. The code looks correct. But as some values grow to excessively large values, they overflow. The comparison operator ultimately gives, as far as I can tell, the good result.

We should check what are the guarantees on comparisons with nan or infinities here.
