### ISSUE TITLE
Lame attempt at a histogram

### ISSUE THREAD

**Issue by michaelcoconnor** [scipy-lectures/scipy-lecture-notes#482]
I refer to https://scipy-lectures.org/intro/scipy/auto_examples/plot_normal_distribution.html. 

It's difficult to see how it is an improvement over [this](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html?highlight=numpy%20random%20normal#numpy.random.normal) or even a passable substitute for it.

For example the blue curve on the plot, which is called a histogram, is not a histogram: See https://www.merriam-webster.com/dictionary/histogram.

You don't need to roll your own bins, you just tell `plt.hist` how many bins you want:

    import numpy as np
    from scipy import stats
    from matplotlib import pyplot as plt
    # Sample from a normal distribution using numpy's random number generator.
    samples = np.random.normal(0.0, 0.1, 10000)
    # Compute a histogram of the sample.
    plt.figure(figsize=(6, 4))
    count, bins, ignored = plt.hist(samples, 30, density=True, label="Histogram of samples")
    pdf = stats.norm.pdf(bins, 0.0, 0.1)
    plt.plot(bins, pdf, label="PDF")
    plt.legend()
    plt.show()

So I would recommend a reference to the other, official numpy doc. Why are you trying to rewrite it?

**Comment by pdebuyl** [comment]
@michaelcoconnor 

Please keep the language correct.

We do not attempt to mimick or replace the official documentation. These lecture notes provide a self-contained pedagogical reference to learn the scientific Python tools.
