### ISSUE TITLE
Menu with transparent background

### ISSUE THREAD

**Issue by rvyh** [scipy-lectures/scipy-lecture-notes#484]
The menu that opens from the 'sandwich' icon has transparent background, so texts overlap and are not readable.

<img width="300" alt="menu" src="https://user-images.githubusercontent.com/62675403/82832501-485d3e80-9e89-11ea-9a7c-a8f9ede9410f.png">

**Comment by pdebuyl** [comment]
Hello, can you tell me at what resolution and on what device this happens? Thank you.

**Comment by rvyh** [comment]
Hi! Macbook pro, 1280 x 800 (default value) retina display. Sandwich icon doesn't appear on the homepage, but on internal pages like http://scipy-lectures.org/intro/intro.html

**Comment by pdebuyl** [comment]
Can you check the result at http://pdebuyl.be/tmp/sln/ ?

**Comment by rvyh** [comment]
Looks better, but there is some white text on the gray background, "Previous topic"
"Next topic":

![menu2](https://user-images.githubusercontent.com/62675403/82961191-9dcd4480-9f8a-11ea-8367-4c14c59fb431.jpg)

And some pages have an empty menu, like this one: http://pdebuyl.be/tmp/sln/intro/numpy/index.html

**Comment by pdebuyl** [comment]
Thank for the update. The display of "previous topic" and "next topic" has been disabled some time ago, I have to check if there was a specific reason for this. The bar at the top of the page has "next" and "previous", it might be related.

**Comment by pdebuyl** [comment]
I fixed the background issue and removed the "next / previous" in the table of content. There still is a next/previous in the header bar of the pages. Some pages have an empty table of content because either the page is a table of content itself or because there is no subsection in the page.

Could you check again the preview at http://pdebuyl.be/tmp/sln/ ?
