### ISSUE TITLE
plot_fftpack: power calc -- shouldn't absolute value of fft be squared?

### ISSUE THREAD

**Issue by EricThomson** [scipy-lectures/scipy-lecture-notes#490]
In plot_fftpack, for the power calculation it takes the absolute value of the fft:

```
# And the power (sig_fft is of complex dtype)
power = np.abs(sig_fft)
```

But isn't the power the square of this quantity?

**Comment by pdebuyl** [comment]
Indeed this is wrong, thank you for noticing it. I fixed it but the fix will only appear at the next release.
