### ISSUE TITLE
fatal: Ambiguous object name: 'HEAD'

### ISSUE THREAD

**Issue by jarrodmillman** [scipy-lectures/scipy-lecture-notes#503]
@pdebuyl @GaelVaroquaux I wanted to make a PR and ran into an issue due to this tag:
https://github.com/scipy-lectures/scipy-lecture-notes/releases/tag/HEAD

Here is what happens:
```
$ git clone git@github.com:scipy-lectures/scipy-lecture-notes.git
$ cd scipy-lecture-notes/
$ git checkout -b sphinx-update
warning: refname 'HEAD' is ambiguous.
fatal: Ambiguous object name: 'HEAD'.
```

Once I get access to this organization, I can fix this. In the meantime, it would be great if someone with permission would delete HEAD tag.

**Comment by pdebuyl** [comment]
Mistake by me. Should be fixed.

**Comment by tbb1984** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
