### ISSUE TITLE
Swig bindings to C/C++/CUDA

### ISSUE THREAD

**Issue by gravitino** [scipy-lectures/scipy-lecture-notes#58]
Are you interested in a section about swig and the interoperability with C/C++ or even CUDA? I could write something about that, if you like.

**Comment by gravitino** [comment]
After two years, I decided to write a boilerplate project for binding CUDA directly to numpy:
https://github.com/gravitino/pyCUREVERSE
Maybe, it is of use for you.

**Comment by esc** [comment]
Interesting. I'll be closing this, feel free to reopen. The section about interfacing with C can be found at:

https://scipy-lectures.github.io/advanced/interfacing_with_c/interfacing_with_c.html
