### ISSUE TITLE
np.core.umath_tests

### ISSUE THREAD

**Issue by jarrodmillman** [scipy-lectures/scipy-lecture-notes#618]
I commented out a section (see https://github.com/scipy-lectures/scipy-lecture-notes/pull/616/commits/da2a21ccc48aca579952a5f1af08649ca8030fb8) using `np.core.umath_tests` in #616 due to this error:
```
_____________________________ [doctest] index.rst ______________________________
1166 
1167     >>> import numpy as np
1168     >>> np.linalg.det(np.random.rand(3, 5, 5))
1169     array([ 0.00965823, -0.13344729,  0.04583961])
1170     >>> np.linalg._umath_linalg.det.signature
1171     '(m,m)->()'
1172 
1173 * we also ship with a few g-ufuncs for testing, ATM::
1174 
1175     >>> import numpy.core.umath_tests as ut
UNEXPECTED EXCEPTION: RuntimeError('cannot load _umath_tests module.')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/doctest.py", line 1334, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest index.rst[149]>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/numpy/core/umath_tests.py", line 13, in <module>
    from ._umath_tests import *
RuntimeError: cannot load _umath_tests module.
/home/runner/work/scipy-lecture-notes/scipy-lecture-notes/advanced/advanced_numpy/index.rst:1175: UnexpectedException
----------------------------- Captured stderr call -----------------------------
```

We need to investigate whether to replace that section and check if the surrounding text needs to be revised.

**Comment by rossbar** [comment]
I think the only thing to be done here (at this stage) is to remove this section. The `_umath_tests` module was [deprecated way back in numpy 1.15](https://numpy.org/doc/stable/release/1.15.0-notes.html#compiled-testing-modules-renamed-and-made-private) and has not been recommended for direct access for a long time.

In principle it would be nice to have a gufunc example... One idea would be to refactor `_umath_tests` to extract the definition of the `matrix_multiply` gufunc from the test definitions. I'm not sure how involved that would be, but IMO it'd be generally beneficial to have at least one example of a generalized ufunc from numpy itself.
