### ISSUE TITLE
remove the list comprehension module from language example

### ISSUE THREAD

**Issue by esc** [scipy-lectures/scipy-lecture-notes#81]
The section at:

http://scipy-lectures.github.com/intro/language/control_flow.html#list-comprehensions

is pretty useless. It has a single example of list comprehensions w/o any further explanation. Best it can do, is confuse students.

**Comment by gertingold** [comment]
This issue is addressed in #456 where I have added a short sentence at least motivating the example. I am closing the issue but it may be reopened of course if the solution proposed in #456 is not found appropriate.

**Comment by esc** [comment]
@gertingold thanks for taking care of this. I think the proposed solution is fine, thanks!
