### ISSUE TITLE
override pylab.rcParams

### ISSUE THREAD

**Issue by esc** [scipy-lectures/scipy-lecture-notes#88]
To avoid that a custom `matplotlib_rc` file will break the plots on
generation, brutally put `pylab.rcParams` to
`pylab.rcParamsDefault` before executing each script.

Was cleaning out my INBOX and found this in an old email from oct 2011, not sure if it is still relevant.

**Comment by GaelVaroquaux** [comment]
This should be done in sphinx-gallery. Cc @titan-C

**Comment by GaelVaroquaux** [comment]
Closing as implement in #327
