### ISSUE TITLE
Issues for "interfacing with C"

### ISSUE THREAD

**Issue by mwiebe** [scipy-lectures/scipy-lecture-notes#90]
1) This is an important read for anyone writing C-API code:

http://docs.python.org/2/c-api/intro.html#objects-types-and-reference-counts

2) Add a disadvantage to using the C-API directly:
- Reference count bugs are easy to create and very hard to track down.

3) Use a single multi-iterator for the npyiter example

4) Links for the numpy c api section:

http://docs.scipy.org/doc/numpy/reference/c-api.array.html
http://docs.scipy.org/doc/numpy/reference/c-api.iterator.html

**Comment by pdebuyl** [comment]
Hi @mwiebe points 1, 2, and 4 were addressed by  @esc in 2013 already and 3 by @seberg this year! It will come online with the next release :-)

**Comment by GaelVaroquaux** [comment]
> Hi @mwiebe points 1, 2, and 4 were addressed by @esc in 2013 already and 3 by @seberg this year! It will come online with the next release :-)

Awesome!! The power of open communities. Thank you so much to all those
involved!!

**Comment by esc** [comment]
🎉
