### ISSUE TITLE
Localization of the notes

### ISSUE THREAD

**Issue by Juanlu001** [scipy-lectures/scipy-lecture-notes#96]
As of Sphinx 1.1, there is the posibility to generate translatable strings (.pot files) from a Sphinx project, like it is done in the Open Data Handbook:

https://github.com/okfn/opendatahandbook#building-the-english-source-for-translation-i18n

which can be later translated, for example, through a crowdsourcing service like Transifex:

https://www.transifex.com/projects/p/opendatahandbook/

(also self-hosted if needed, otherwise the platform is free for open source projects)

Would it be possible to have this for the notes? For the case of Spanish language, we started our own translation:

https://github.com/Pybonacci/scipy-lecture-notes-ES

but it's very difficult to catch up with the changes upstream, and everything gets messed up. I would like to know if there would be the possibility, otherwise translating is probably not worth the effort.

**Comment by GaelVaroquaux** [comment]
I am closing this issue, as there has not been activity in 3 years, and I am not sure that we have the bandwidth to undertake such an endeavor.
